---
# defaults file for nginx

# System user for process
# nginx_user: "www-data"
nginx_user: "root"

# System group for process
# nginx_group: "www-data"
nginx_group: "root"

# Nginx package parameters
nginx_ppa_version: mainline
nginx_package_name: "nginx"

# Nginx.conf will be created using these directives - the role will not work if they do not exist
core:
  - name: main_settings # Required
    user: root
    worker_processes: auto
    error_log: /var/log/nginx/error.log warn
    pid: /run/nginx.pid
    worker_rlimit_nofile: 16500
    worker_connections: 8192
    include: /etc/nginx/mime.types
    default_type: application/octet-stream
    server_names_hash_bucket_size: 64
    access_log: /var/log/nginx/access.log access_custom buffer=16k
    sendfile: "on"
    keepalive_timeout: 65
    gzip: "on"
    gzip_comp_level: 5
    gzip_http_version: 1.0
    gzip_proxied: any
    gzip_min_length: 1100
    gzip_buffers: 16 8k
    gzip_types: text/plain text/css application/x-javascript text/xml application/xml application/xml+rss text/javascript application/json application/javascript image/svg+xml
    gzip_disable: MSIE [1-6].(?!.*SV1)
    gzip_vary: "on"
    server_tokens: "off"
    proxy_headers_hash_bucket_size: 128
    client_body_buffer_size: 15M
    client_max_body_size: 50M
    proxy_max_temp_file_size: 0
    fastcgi_buffers: 4 256k
    fastcgi_busy_buffers_size: 256k
    fastcgi_temp_file_write_size: 512k

# Upstream configs will be created using these directives - uncomment them if you need an upstream(s)
#upstream:
#  - name: my-upstream-application_1  # Required
#    server: example.com # domain.com (http) OR address:port (tcp)
#    listen: 12345
#    proxy_protocol: http # http or tcp
#  - name: my-upstream-application_2  # Required
#    server: 10.0.0.1:7777 # domain.com (http) OR address:port (tcp)
#    listen: 56789
#    proxy_protocol: tcp # http or tcp

upstream: []
