---

- name: Setting host facts about disks on machine
  ansible.builtin.set_fact: 
    tf_disks: "{{ ansible_facts.device_links.ids }}"

- name: "Read device names"
  set_fact: 
    device: "{{ DEVICE_PREFIX | product(tf_disks.values () | flatten | map ('regex_search', '^[a-z]{6}[-]{1}[a-z]{4}[0-9]{2}$') | select())| map('join', '/') | join (',') }}"

- name: Create or rebuild volume group on top of /dev/ ...
  community.general.lvg:
    vg: "{{ VG_NAME }}"
    pvs: "{{ device }}"
    pvresize: true
  
- name: Allocation space of the PVs for VG
  community.general.lvol:
    vg: "{{ VG_NAME}}"
    lv: "{{ LV_NAME }}"
    size: "{{ VG_SIZE }}"
    resizefs: true

- name: Create a logical volume of VG
  community.general.lvol:
    vg: "{{ VG_NAME }}"
    lv: "{{ LV_NAME }}"
    size: "{{ LV_SIZE }}"
    pvs: "{{ device }}"
    force: true

- name: Activate a volume group
  community.general.lvg:
    state: present
    vg: "{{ VG_NAME }}"
    pvs: "{{ device }}"

- name: Create a filesystem
  community.general.filesystem:
    dev: "/dev/{{ VG_NAME }}/{{ LV_NAME }}"
    fstype: "{{ TYPE_FS }}"
    state: present
    resizefs: true
    
- name: Mount lvm to folder
  mount:
    name: "{{ folder_mount_point }}"
    fstype: "{{ TYPE_FS }}"
    src: "/dev/{{ VG_NAME }}/{{ LV_NAME }}"
    state: mounted

