- name: Template a file to /etc/netplan/routes.yaml
  ansible.builtin.template:
    src: routes.j2
    dest: /etc/netplan/routes.yaml
    owner: root
    group: root
    mode: '0600'

- name: Apply netplan
  ansible.builtin.shell: netplan apply
