---
- name: Apt update
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Add mandatory apt packages
  ansible.builtin.apt:
    name: "{{ mandatory_apt_packages }}"
    update_cache: true
    state: present

- name: Add mandatory pip packages
  ansible.builtin.pip:
    name: "{{ mandatory_pip_packages }}"
    state: present

- name: Get CARoot certificate
  ansible.builtin.get_url:
    url: '{{ caroot_certificate_chain_url }}'
    dest: "/usr/local/share/ca-certificates/CARoot.crt"
    force: true
    mode: '0644'
    validate_certs: false

- name: Update certification index
  ansible.builtin.shell: /usr/sbin/update-ca-certificates
  register: shell_result
  changed_when: "'0 added, 0 removed' not in shell_result.stdout"

- name: Install apt packages
  ansible.builtin.apt:
    name: "{{ apt_packages }}"
    state: present
  when:
    - apt_packages | length > 0

- name: Install pip packages
  ansible.builtin.pip:
    name: "{{ pip_packages }}"
    state: present
  when:
    - pip_packages | length > 0

- name: Upgrade installed packages
  ansible.builtin.apt:
    name: "{{ apt_upgrade_packages }}"
    state: latest
    only_upgrade: true
  when:
    - apt_upgrade_packages | length > 0
