---
- name: Adding APT repository key
  ansible.builtin.apt_key:
    url: "http://nginx.org/keys/nginx_signing.key"

- name: Add official APT repository
  ansible.builtin.apt_repository:
    repo: "deb http://nginx.org/packages/{{ nginx_ppa_version }}/{{ ansible_distribution|lower }}/ {{ ansible_distribution_release }} nginx"
    state: present

- name: Update APT package manager repositories cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Ensure nginx will be reinstalled if the PPA was just added
  ansible.builtin.apt:
    name: nginx
    state: absent

- name: Ensure nginx is installed
  ansible.builtin.apt:
    name: "{{ nginx_package_name }}"
    state: present

- name: Write nginx core config
  ansible.builtin.template:
    src: "core.conf.j2"
    dest: "/etc/nginx/nginx.conf"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: "0644"
  notify:
    - Reload nginx

- name: Clean up old upstreams configs & directories
  ansible.builtin.file:
    path: '{{ item }}'
    state: absent
  with_items:
    - /etc/nginx/conf.d
    - /etc/nginx/stream.d

- name: Create new empty upstreams directories
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    mode: 0755
    group: "{{ nginx_user }}"
    owner: "{{ nginx_group }}"
  with_items:
      - /etc/nginx/conf.d
      - /etc/nginx/stream.d

- name: Enable module ngx_http_stub_status_module for nginx exporter
  ansible.builtin.template:
    src: "http_stub_status_module.j2"
    dest: "/etc/nginx/conf.d/http_stub_status_module.conf"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: "0644"
  notify:
    - Restart nginx

- name: Write an upstream config if needed (/etc/nginx/conf.d)
  ansible.builtin.template:
    src: "upstream.conf.j2"
    dest: "/etc/nginx/conf.d/{{ item.name }}.conf"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: "0644"
  loop: "{{ upstreams }}"
  register: nginx_conf
  notify:
    - Reload nginx
  when:
    - upstreams is defined
    - item.proxy_protocol == 'http'
    - upstreams | type_debug == 'list'
    - upstreams | length > 0

- name: Write an upstream config if needed (/etc/nginx/stream.d)
  ansible.builtin.template:
    src: "upstream.conf.j2"
    dest: "/etc/nginx/stream.d/{{ item.name }}.conf"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: "0644"
  loop: "{{ upstreams }}"
  register: nginx_conf
  notify:
    - Reload nginx
  when:
    - upstreams is defined
    - item.proxy_protocol == 'tcp'
    - upstreams | type_debug == 'list'
    - upstreams | length > 0
