---
- name: Create group nginx_exporter
  ansible.builtin.group:
    name: nginx_exporter
    system: true
    state: present

- name: Create nginx_exporter user
  ansible.builtin.user:
    name: nginx_exporter
    create_home: no
    group: nginx_exporter

- name: Download nginx exporter binary
  ansible.builtin.get_url:
    url: "{{ NEXUS_URL }}/repository/nexus-infra-raw/nginx_exporter/{{ NGINX_EXPORTER_VERSION }}/nginx-prometheus-exporter"
    dest: /usr/bin/nginx_exporter
    mode: "0755"

- name: Create nginx exporter service config
  ansible.builtin.template:
    src: "nginx_exporter.d/systemd-unit.j2"
    dest: "/etc/systemd/system/nginx_exporter.service"
    owner: "root"
    group: "root"
    mode: "0744"

- name: Create nginx exporter consul file
  ansible.builtin.template:
    src: "consul.d/nginx-exporter.j2"
    dest: "/etc/consul.d/nginx-exporter-service.json"
    owner: "root"
    group: "root"
    mode: "0755"

- name: Enable nginx exporter service and reload systemd
  ansible.builtin.systemd:
    state: started
    enabled: true
    daemon_reload: true
    name: nginx_exporter

- name: Restart systemd-unit consul
  ansible.builtin.systemd_service:
    state: restarted
    name: consul